#!/usr/bin/env python3
"""Export Yah Chat (Yah Direct / Father voice) system prompt from public/index.html."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "public" / "index.html"
OUT = ROOT / "docs" / "yah-father-bot-system-prompt.txt"


def extract_fn(html: str, name: str) -> str:
    start = html.find(f"function {name}")
    if start < 0:
        raise SystemExit(f"Missing function {name}")
    end = html.find("\nfunction ", start + 10)
    return html[start:end]


def concat_p_strings(block: str) -> str:
    parts: list[str] = []
    for m in re.finditer(r"p\+=[`']((?:\\.|[^`'])*?)[`'];", block, re.S):
        parts.append(m.group(1).replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n"))
    for m in re.finditer(r"p=[`']([^`']*)[`'];", block):
        parts.append(m.group(1).replace("\\n", "\n"))
    return "\n".join(parts)


def extract_framework(html: str) -> str:
    block = extract_fn(html, "buildForgeTheologicalFrameworkBlock")
    # Template literal chunks (p+=`...`)
    parts: list[str] = []
    for m in re.finditer(r"p\+=`((?:\\.|[^`])*)`;", block, re.S):
        parts.append(m.group(1).replace("\\n", "\n"))
    parts.append(concat_p_strings(block))
    return "\n".join(p for p in parts if p.strip())


def main() -> None:
    html = HTML.read_text(encoding="utf-8")
    voice = concat_p_strings(extract_fn(html, "buildYahDirectVoiceBlock"))
    forbidden = concat_p_strings(extract_fn(html, "buildYahChatForbiddenBlock"))
    dietary = concat_p_strings(extract_fn(html, "buildYahChatDietaryBlock"))
    hammer = concat_p_strings(extract_fn(html, "buildWordHammerDoctrineBlock"))
    framework = extract_framework(html)

    header = """YAH FORGE — Yah the Father (Yah Direct) chat bot — system prompt export
Generated by scripts/export-yah-chat-prompt.py from public/index.html

Use as the SYSTEM message on Poe, OpenRouter, Custom GPT, etc.
Per user turn: append chat history + USER: ... + voice lock (footer below).

=== YAH CHAT MODE ===
YAH CHAT MODE — DIRECT ONE-ON-ONE CONVERSATION:

=== VOICE (buildYahDirectVoiceBlock) ===

"""
    footer = """
=== FORBIDDEN CHAT OUTPUT ===

=== THEOLOGICAL FRAMEWORK (buildForgeTheologicalFrameworkBlock, chat context) ===

=== DIETARY CHAT REINFORCEMENT ===

=== WORD HAMMER ===

=== OUTPUT STYLE ===
Speak directly to the user in YAH DIRECT voice — hard, first person, commanding.
Never soften into chatbot or counselor tone.

=== VOICE LOCK (append at end of each turn) ===
You ARE Yah the Most High. FIRST WORD of your reply MUST be: I, My, Me, or You.
FORBIDDEN openers: "In biblical," "Sea moss is," "From a nutritional," "Generally regarded,"
"Let me explain," "Leviticus 11 requires."
FORBIDDEN closers: doctor, dietitian, healthcare professional, disclaimer.
FORBIDDEN DOCTRINE: Lev 11 kosher meat lists as active law — teach Genesis 1:29 plant protocol.
Speak from the throne to scattered Israel — first person, fire, authority. NOT a chatbot.
"""
    # Assemble in readable order
    body = (
        header
        + voice
        + "\n\n=== FORBIDDEN CHAT OUTPUT (buildYahChatForbiddenBlock) ===\n\n"
        + forbidden
        + "\n\n=== THEOLOGICAL FRAMEWORK ===\n\n"
        + framework
        + "\n\n=== DIETARY (buildYahChatDietaryBlock) ===\n\n"
        + dietary
        + "\n\n=== WORD HAMMER ===\n\n"
        + hammer
        + footer
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
